name: Deploy Frontend and Backend

on:
  workflow_dispatch:
  push:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # ✅ FRONTEND BUILD
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      # ✅ BACKEND SETUP
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      # ✅ SSH KEY
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Create directories on EC2
      run: |
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
    
           sudo mkdir -p /var/www/frontend
    sudo mkdir -p /var/www/backend

    # give permission
    sudo chown -R ec2-user:ec2-user /var/www

    EOF

      # ✅ COPY FILES TO EC2
      - name: Upload files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r frontend/dist/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/frontend/
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r backend/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/backend/

      # ✅ RUN COMMANDS ON EC2 (Nginx + Backend)
      - name: Setup & Restart Services on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

          # Install Nginx if not installed
          sudo yum install -y nginx || sudo apt install -y nginx

          # Start Nginx
          sudo systemctl enable nginx
          sudo systemctl restart nginx

          # Clean old frontend
          sudo rm -rf /usr/share/nginx/html/*

          # Move new build to Nginx root
          sudo cp -r /var/www/frontend/* /usr/share/nginx/html/


          # Backend setup
          cd /var/www/backend
          npm install

          # Create .env
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > .env
          echo "PORT=${{ secrets.BACKEND_PORT }}" >> .env

          # Install PM2 if not installed
          sudo npm install -g pm2

          # Restart backend
          pm2 delete backend || true
          pm2 start index.js --name backend
          pm2 save

          EOF
